# Do not keep production secrets in the repository,
# instead read values from the environment.
# secret token (min 30 chars) - only needed for production - use '$ rake secret' to generate

# Add account credentials and API keys here.
# See http://railsapps.github.com/rails-environment-variables.html

development:
  secret_key_base: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

  ## general prefs
  app_url: bor.ello.dev
  parent_url: ello.co
  base_site_title: 'The Social Media Bill of Rights'
  base_company_name: 'Ello'
  general_email_address: 'support@ello.co'
  twitter_username: elloword

  ## lockup password
  lockup_codeword:

  ## postmark stuff
  postmark_key: 

  # mailcatcher, set to true to turn on in dev mode
  mail_catcher:

  ## smtp email stuff (or sendgrid)
  email_address: 'smtp.sendgrid.net'
  email_port: 587
  email_domain:
  email_username:
  email_password:
  email_authentication: 'plain'

  ## mailchimp stuff
  mailchimp_key:
  mailchimp_list_id:

test:
  secret_key_base: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

production:
  secret_key_base: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

  ## general prefs
  app_url: bor.ello.dev
  parent_url: ello.co
  base_site_title: 'The Social Media Bill of Rights'
  base_company_name: 'Ello'
  general_email_address: 'support@ello.co'
  twitter_username: elloword

  ## lockup password
  lockup_codeword:

  ## postmark stuff
  postmark_key: 

  # mailcatcher, set to true to turn on in dev mode
  mail_catcher:

  ## smtp email stuff (or sendgrid)
  email_address: 'smtp.sendgrid.net'
  email_port: 587
  email_domain:
  email_username:
  email_password:
  email_authentication: 'plain'

  ## mailchimp stuff
  mailchimp_key:
  mailchimp_list_id:
